# Generated by Django 4.2.4 on 2023-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
