# Generated by Django 4.2.4 on 2023-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blogpost_author_blogpost_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
