# Generated by Django 4.2.4 on 2023-09-12 03:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
