# Generated by Django 4.2.4 on 2023-09-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_mymodel_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
